services:
  server-tuto_app:
    container_name: server_tuto_app
    image: nginx:1.25-alpine3.18
    restart: unless-stopped
    volumes:
      - ./symfony:/www/symfony
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8080:80'

  php_tuto_app:
    container_name: php_tuto_app
    build: ./docker/php
    restart: unless-stopped
    working_dir: /www/symfony
    user: "1000"
    volumes:
      - ./symfony:/www/symfony
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres_tuto_app
    env_file:
      - .env

  postgres_tuto_app:
    container_name: postgres_tuto_app
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
volumes:
  postgres_data: